

export const GET_ITEM_LIST_LOADING ="GET_ITEM_LIST_LOADING"
export const GET_ITEM_LIST_SUCESSS ="GET_ITEM_LIST_SUCESSS"
export const GET_ITEM_LIST_ERROR ="GET_ITEM_LIST_ERROR"

export const SEARCH_ITEM_LIST_LOADING ="SEARCH_ITEM_LIST_LOADING"
export const SEARCH_ITEM_LIST_SUCESSS ="SEARCH_ITEM_LIST_SUCESSS"
export const SEARCH_ITEM_LIST_ERROR ="SEARCH_ITEM_LIST_ERROR"



export const ADD_ITEM_TO_CART_LOADING ="ADD_ITEM_TO_CART_LOADING"
export const ADD_ITEM_TO_CART_SUCESSS ="ADD_ITEM_TO_CART_SUCESSS"
export const ADD_ITEM_TO_CART_ERROR ="ADD_ITEM_TO_CART__ERROR"

export const REMOVE_ITEM_TO_CART ="REMOVE_ITEM_TO_CART"

